# Welcome to Jekyll!
#

# Site settings
title: OniFriends
description: |

owner: OniFriends # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: onifriends@yahoo.com
baseurl: "https://teaonme.github.io/" # the subpath of your site, e.g. /blog
url: "https://teaonme.github.io/" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/Oni_Friends
  linkedin-square: https://www.linkedin.com/in/oni-friends-27622b233/
  Discord: https://discord.gg/RtxXydCHtD
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:
  #Discord:
# Build settings
markdown: kramdown
#sass:
#  style: compressed
